### ISSUE TITLE
Alter error details

### ISSUE THREAD

**Issue by Codypinto23** [jryther/ChatApp-Backend#1]
Consider altering nformation returned from the API. An attacker testing the APIs now knows there's not a user assigned with this ID. They can now test IDs until they get a different error, meaning they've found a valid ID.
Go with a more obscure error like "Invalid Request"

Dumb, I know, but l figured I'd throw it out there.

Project looks great by the way!! Super cool you built a full stack app with video!! 

https://github.com/jryther/ChatApp-Backend/blob/131acc02ffcc02bfd1fad2c954fcb1fea3e11e3a/src/main/java/com/joshryther/chatappbackend/controller/UserAccountController.java#L77

**Comment by jryther** [comment]
Good to know.  I'll make sure to add this to the next round of updates.
